### ISSUE TITLE
rviz of car's moving

### ISSUE THREAD

**Issue by xiaozhi12345678** [coincar-sim/coincarsim_getting_started#4] opened 2019-04-18 14:59 UTC
Hi,I want to ask a question.If I want to make the car in rviz move by my publishing GPS or (x,y)position message,how can I do it?than you!

**Comment by m-naumann** [comment] 2019-04-19 21:07
You can send an [AbsoluteTrajectoryWithID](https://github.com/coincar-sim/simulation_only_msgs/blob/release/msg/AbsoluteTrajectoryWithID.msg)-message to the simulation management on [this](https://github.com/coincar-sim/simulation_initialization_ros_tool/blob/release/launch/_whole_framework.launch#L11) topic for instance.

GPS positions are only supported as initialization, afterwards, the movement of all objects need to be in Cartesian coordinates (x,y). You can, however, internally project lat/lon to x/y and back as you like.

**Comment by xiaozhi12345678** [comment] 2019-04-26 14:39
I am sorry to trouble you, that I write a node to publish (x,y) position on the topic "/sim/object_initialization",is it necessary to shielding planning node in sample_vehicle.launch?And the terminal print "/localization_mgmt: Received DesiredMotionAbsolute of Object that does not exist! I discard this message! (id=1)",the car didn't move. Is there something don't do?thank you!

**Comment by m-naumann** [comment] 2019-04-29 06:07
Sorry, I can't trace your problem with this information. You could fork the repos you changed and refer the specific lines, such that I could have a look. 

The position must not be published under `/sim/object_initialization`, but under `/sim/desired_motion_absolute` or `/sim/desired_motion`, further, I strongly recommend to use and pass the  [launchfile arguments](https://github.com/coincar-sim/simulation_initialization_ros_tool/blob/release/launch/_whole_framework.launch#L11).

**Comment by xiaozhi12345678** [comment] 2019-04-29 13:54
Emm, hello ,I use the function findnearest to locate GPS point in which lanelet,but it didn't find correct lanelet id.
And my osm map is in China,I modify the origin in code.
I selected GPS point in my osm map with JOSM,in JOSM I use utm 50N projection,but I think the projection doesn't matter because I make comparing with different projection in JOSM with same location and their GPS similarily.
Is there something I need modify?How can I get the right lanelet id?thank you!

**Comment by m-naumann** [comment] 2019-04-29 14:12
Now duplicate of https://github.com/fzi-forschungszentrum-informatik/Lanelet2/issues/22

**Closed as completed by m-naumann** 2019-04-29 14:12 UTC
