### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by noone3001** [coincar-sim/coincarsim_getting_started#6] opened 2020-02-11 02:37 UTC
Sorry to bother you. When I build the whole project, an error stopped me:

**Errors**     << sim_sample_communication_ros_tool:make /catkin_ws/logs/sim_sample_communication_ros_tool/build.make.000.log
**/bin/sh: 1: cd: can't cd** to /catkin_ws/build/sim_sample_communication_ros_tool/$<TARGET_FILE_DIR:sim_sample_communication_ros_tool-comm_module-nodelet>
make[2]: *** [/catkin_ws/devel/.private/sim_sample_communication_ros_tool/lib/libsim_sample_communication_ros_tool-comm_module-nodelet.so.1.0.0] Error 2
make[2]: *** Deleting file '/catkin_ws/devel/.private/sim_sample_communication_ros_tool/lib/libsim_sample_communication_ros_tool-comm_module-nodelet.so.1.0.0'
make[1]: *** [CMakeFiles/sim_sample_communication_ros_tool-comm_module-nodelet.dir/all] Error 2
make: *** [all] Error 2

It has confused me for few days. Could you help me ? Looking forward to your reply.

**Comment by m-naumann** [comment] 2020-02-11 08:26
Thanks for reporting. I could reproduce it in travis ci. We will look into that. I opened an issue in the respecitive package: https://github.com/coincar-sim/sim_sample_communication_ros_tool/issues/2

**Comment by m-naumann** [comment] 2020-02-11 17:46
It's fixed with https://github.com/KIT-MRT/mrt_cmake_modules/commit/2364cf7b06d89b93406fc4244ffc0c02e9962652

Please update the mrt_cmake_modules and test again. In travis it works now

**Comment by noone3001** [comment] 2020-02-18 10:36
Sorry to bother you. I got a new problem to build the project.
Errors     << lanelet2_validation:make /catkin_ws/logs/lanelet2_validation/build.make.000.log         
/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so.0.9.0: undefined reference to `pugi::xml_node::operator void (*)(pugi::xml_node***)() const'
/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so.0.9.0: undefined reference to `pugi::xml_attribute::as_llong(long long) const'
/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so.0.9.0: undefined reference to `pugi::xml_attribute::operator=(long long)'
/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so.0.9.0: undefined reference to `pugi::xml_attribute::operator void (*)(pugi::xml_attribute***)() const'
/catkin_ws/devel/.private/lanelet2_io/lib/liblanelet2_io.so.0.9.0: undefined reference to `pugi::xml_attribute::as_double(double) const'
collect2: error: ld returned 1 exit status
make[2]: *** [/catkin_ws/devel/.private/lanelet2_validation/lib/lanelet2_validation/lanelet2_validate] Error 1
make[1]: *** [CMakeFiles/lanelet2_validation-lanelet2_validate-exec.dir/all] Error 2
make: *** [all] Error 2
Whether it's the problem of the corresponding module or the problem of  environment dependence ?
Could you help me ?

**Comment by m-naumann** [comment] 2020-02-18 13:36
Looks like linking to pugixml does not work. Please try to build lanelet2 separately first: https://github.com/fzi-forschungszentrum-informatik/Lanelet2 and if it doesn't work open an issue there.

**Comment by noone3001** [comment] 2020-02-18 14:33
Thank you. I tried as you told me, but I got the same error displayed, with building lanelet2 separately. And what do you mean that linking to pugixml does not work? I am sure that I have gotten libpugixml-dev installed as the README told. If the libpugixml-dev (for lanelet2) is a specific version? In my PC Ubuntu16.04, libpugixml-dev is already the newest version (1.7-2).

**Comment by m-naumann** [comment] 2020-02-19 10:45
Please try building it using the provided docker as in https://travis-ci.org/fzi-forschungszentrum-informatik/Lanelet2/jobs/651628659

If that doesn't work, please open an issue in lanelet2, as this is not a coincarsim-issue.

**Comment by noone3001** [comment] 2020-02-20 02:54
Finally, as you thought, it's a linking problem of pugixml. Now, I fixed it in my PC, and simulation does work.

**Closed as completed** 2020-02-20 02:54 UTC
